---
title: "Assessment1 part1"
author: "Vishnu"
date: "`r Sys.Date()`"
output: html_document
---
#part1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# RMarkdown editing 
** R Markdown is a file format for making dynamic documents with R. 
* An R Markdown document is written in markdown an easy-to-write plain text format and contains chunks of embedded R code.

This text is *Italic letters* 

This text is **Bold letters **

### Click bellow to learn a lesson about RMarkdown

* visit : https://rmarkdown.rstudio.com/lesson-8.html 

##or 

**visit: [click here](https://rmarkdown.rstudio.com/lesson-8.html )

```{r}
library(tidyverse)


#install.packages("lubridate")
library(lubridate)
library(dplyr)
fastfood <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")
```


```{r}
library(data.table)
head(fastfood,10)
```

```{r}
library(knitr)
kable(fastfood[1:10,1:5])

```

```{r}
filt_data <- filter(fastfood, calories > 1000)
head(filt_data)
```

```{r}
library(dplyr)
filt_data <- filter(fastfood, total_fat > 40 , total_carb > 80)
dont_eat_this <- filt_data
head(dont_eat_this)

```

```{r}
#install.packages("skimr")
library(skimr)
head(fastfood)

fastfood %>%
  select(restaurant,calories, total_fat,total_carb)%>%
  mutate(heavyfoods = case_when(calories > 500 ~ "heavy", calories < 250 ~ "low", TRUE ~ "average"))
count(fastfood)
skim(fastfood)
```

```{r}
fastfood %>%
  count(restaurant, sort = TRUE, name = "observations")%>%
top_n(10)
```
```{r}
fastfood %>%
  group_by(restaurant) %>%
  summarise(averagecal = sum(calories), max_fat = max(total_fat), min_cholesterol = min(cholesterol)) %>%
  ungroup() %>%
  kable()
```
```{r}

fastfood %>%

  ggplot(aes(restaurant, total_fat, fill = restaurant)) +
  geom_col() +
  coord_flip()
  # Data viz will be more appealing to look into the business. And, it is easy to understand through graphics and charts when compared to a written document comprising text and numbers. Professional way.
  
```

